name: Build My Application
# This workflow is triggered on pushes to the repository.
on: push

jobs :
  build:
    # Job name is Greeting
    name: Build our app
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps :
      # # This step uses GitHub's hello-world-javascript-action: https://github.com/actior
      # - name: Hello world
      # uses: actions/hello-world-javascript-action@v1
      # with: 
      #   who-to-greet: 'Mona the Octocat!'
      # id: hello
      # # This step prints an output (time) from the previous step's action.
      - name: Print Current Directory
      run: pwd
      - name: List file in Directory
      run: ls