name: Build My Application
on: push

jobs :
  build:
    name: Build our app
    runs-on: ubuntu-latest
    steps :
      - name: Pull Code
        uses: actions/checkout@v3
      - name: Print Current Directory
        run: pwd
      - name: List file in Directory
        run: ls
      - name: Check Dotnet Cli
        run: dotnet
      - name: Check NPM Cli
        run: npm